"""
This file is generated by an accompanying org file.
Do not edit by hand.
"""

import xarray as xr
from typing import Union

Truth = xr.DataArray

Prediction = xr.DataArray

Loss = xr.DataArray

Weight = xr.DataArray

Series = Union[Truth, Loss]
